### PR TITLE
 fix txt and ordering issue with pandoc 

### LINKED ISSUE #434: [File format] RTF -> TXT
**Describe the file format**
RTF (Rich Text Format)

**Describe the expected behavior**
Expected behavior would be simply converting the document to plain text. Currently, this routes through JSON and produces garbage data.

**Provide reference implementations**
I believe https://github.com/sigmaSd/stripRtf would be of use to this.

**Do you plan on implementing this yourself?**
No

### PR DESCRIPTION
**Pull request by neko782**
fixes #434

there was a bug where we renamed pandoc's "plain" to "text" which caused it to not work at all and where json and xml routes would get picked instead of obviously better routes.

### CODE REVIEW

File: src/handlers/pandoc.ts [hunk 1]
```diff
@@ -175,7 +175,8 @@ class pandocHandler implements FormatHandler {
     outputFormats.forEach(format => allFormats.add(format));
 
     this.supportedFormats = [];
-    for (let format of allFormats) {
+    for (const internal of allFormats) {
+      let format = internal;
```
Comment (p2r3) [inline src/handlers/pandoc.ts:179]: Confused why this was necessary, but okay.

Comment (neko782) [reply src/handlers/pandoc.ts:179]: preserves the format pandoc gives in case we change the display name any other formats other than plain
